#pragma once

#include <iostream>
#include <stdlib.h>
#include <vector>
#include <string>
#include <cfloat>
#include <cstdint>
#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <math.h>
#include <assimp/Importer.hpp>
#include <assimp/scene.h>
#include <assimp/postprocess.h>
#include <ft2build.h>
#include FT_FREETYPE_H
#include "stb_image.h"

#include "consts.h"
#include "types.h"
#include "utils.h"

#include "Texture.h"
#include "TextureArray.h"
#include "Shader.h"
#include "Window.h"
#include "Mesh.h"
#include "Model.h"
#include "Object.h"
#include "Terrain.h"
#include "Water.h"
#include "Skybox.h"
#include "Airplane.h"
#include "AiAirplane.h"
#include "Boosts.h"
#include "Checkpoints.h"
#include "StartLine.h"
#include "Sprite.h"
#include "Font.h"
#include "Text.h"
#include "Camera.h"
#include "Game.h"
